### PR TITLE
Fixing IV bug in Ciphering Manager

### PR DESCRIPTION
**Pull request by TapuGithub**
Fixing IV bug in Ciphering Manager - de facto it's not used. Also all standards say(5.1.2): The initial chaining value for CBC modes shall be zero and default IV values in case you'll pass null will be random.

### CODE REVIEW

**Comment by pmoerenhout** [comment]
Hi Victor, I added the commits you have done. Thanks. My plan is also to implement the SMS-CB, HTTPS and CAT-TP modes. Any other ideas?

**Comment by TapuGithub** [comment]
Hello Pim, 
May be it will be useful to think about third party security support - standards allow it, but now you cannot use custom algorithms even without custom security parameters. 
So I would have added transformation parameters to card profile and maybe overloaded versions of security manager with custom IV etc.

**Comment by pmoerenhout** [comment]
Sounds good. I was also thinking of removing all the XML code. And adding some enum for the possible modes like SMS-PP, SMS-CB, CAT-TP, HTTPS, in combination with the SecurityBytes. Is the cipheringMasterKey and signatureMasterKey needed and used by you, as I never needed that functionality...

**Comment by TapuGithub** [comment]
I don't know about XML removal. I've added to be able to export packages to easily human and readable  format. Think this is important. May be some other format will be better - AVRO for example: strictly typed, exporting to binary and json, apache first level project. 

And about master keys - it was really a one customer request: they didn't have unique key for each card, instead they had master key and procedure to get card key from master key + ICCID. Don't know if it's common or not. I think you could move master keys from profile - user can use ICCIDKeyGenerator directly if needed.

**Pull request closed without merging**
